version: '3'

services:
  app:
    container_name: app_laravel12
    build: .
    ports:
        -   "8000:8000"
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
      - ./php.ini:/usr/local/etc/php/php.ini

  redis:
      image: redis:latest
      container_name: redis_for_laravel_octance
      ports:
          -   "63792:6379"
